version: '3'
services:
  attacker:
    image: attacker:latest
    networks:
      internet:
        ipv4_address: 172.16.238.10
    volumes:
      - ../scripts:/scripts
      - ../traffic:/traffic
      - ../signals:/signals
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/data_exfiltration_malicious.pcap & python3 -u /scripts/attacker/data_exfiltration.py 2>&1 | tee /tmp/attack_log.txt;
      touch /signals/attacker_done_$${SIMULATION_ID};
      tail -f /dev/null
      "
    environment:
      - SIMULATION_ID
      - PYTHONUNBUFFERED=1
    depends_on:
      - firewall
    
  user:
    image: user:latest
    networks:
      internet:
        ipv4_address: 172.16.238.11
    volumes:
      - ../scripts:/scripts
      - ../traffic:/traffic
      - ../signals:/signals
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/data_exfiltration_benign.pcap & python3 /scripts/user/normal_user_activity2.py;
      touch /signals/user_done_$${SIMULATION_ID};
      tail -f /dev/null
      "
    environment:
      - SIMULATION_ID
    depends_on:
      - firewall

  firewall:
    image: firewall:latest
    networks:
      internet:
        ipv4_address: 172.16.238.2
      dmz:
        ipv4_address: 172.16.239.2
      internal:
        ipv4_address: 172.16.240.2
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv4.ip_forward=1
    depends_on:
      - php_server
      - internal_server

  php_server:
    image: php_server:latest
    networks:
      dmz:
        ipv4_address: 172.16.239.10
    volumes:
      - ../scripts/php_server:/app
    cap_add:
      - NET_ADMIN
    command: >
        sh -c "ip route add 172.16.240.0/24 via 172.16.239.2 && apache2-foreground"

  db:
    image: mysql:5.7
    networks:
      dmz:
        ipv4_address: 172.16.239.11
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: vulnerable_db
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ../scripts/php_server/mysql_data:/var/lib/mysql

  internal_server:
    image: internal_server:latest
    networks:
      internal:
        ipv4_address: 172.16.240.10
    volumes:
      - ../scripts/internal_server:/app

networks:
  internet:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24
  dmz:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.239.0/24
  internal:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.240.0/24