version: '3'
services:
  attacker:
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/ftp_malicious.pcap & python3 /scripts/attacker/ftp_bruteforce.py;
      touch /signals/attacker_done_$${SIMULATION_ID};
      tail -f /dev/null"
    image: attacker:latest
    networks:
    - simulation_network
    volumes:
    - ../scripts:/scripts
    - ../traffic:/traffic
    - ../signals:/signals
    depends_on:
      - ftp_server
    environment:
      - SIMULATION_ID

  user:
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/ftp_benign.pcap & python3 /scripts/user/ftp_transfer.py;
      touch /signals/user_done_$${SIMULATION_ID};
      tail -f /dev/null"
    image: user:latest
    networks:
    - simulation_network
    volumes:
    - ../scripts:/scripts
    - ../traffic:/traffic
    - ../signals:/signals
    environment:
      - FTP_HOST=ftp_server
      - FTP_USER=ftpuser
      - FTP_PASSWORD=ftppassword
    depends_on:
      - ftp_server
    environment:
      - SIMULATION_ID

  ftp_server:
    image: ftp_server:latest
    networks:
      - simulation_network
    ports:
      - '21:21'
      - '30000-30009:30000-30009'
    command: >
      /bin/bash -c "
      mkdir -p /traffic &&
      chmod 777 /traffic &&
      /usr/sbin/vsftpd /etc/vsftpd.conf;tail -f /dev/null
      "
  
networks:
  simulation_network:
    driver: bridge

