version: '3'
services:
  attacker:
    image: attacker:latest
    networks:
      simulation_network:
        ipv4_address: 172.16.238.10
    volumes:
      - ../scripts:/scripts
      - ../traffic:/traffic
      - ../signals:/signals
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/ssh_bruteforce_malicious.pcap & python3 /scripts/attacker/ssh_bruteforce.py;
      touch /signals/attacker_done_$${SIMULATION_ID};
      tail -f /dev/null
      "
    depends_on:
      - ssh_server
    environment:
      - SIMULATION_ID

  user:
    image: user:latest
    networks:
      simulation_network:
        ipv4_address: 172.16.238.11
    volumes:
      - ../scripts:/scripts
      - ../traffic:/traffic
      - ../signals:/signals
    command: >
      /bin/bash -c "
      tcpdump -i any -w ../traffic/ssh_bruteforce_benign.pcap & python3 /scripts/user/ssh_normal_usage.py;
      touch /signals/user_done_$${SIMULATION_ID};
      tail -f /dev/null
      "
    depends_on:
      - ssh_server
    environment:
      - SIMULATION_ID

  ssh_server:
    image: ssh_server:latest
    networks:
      simulation_network:
        ipv4_address: 172.16.238.12
    ports:
      - "2222:22"

networks:
  simulation_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.238.0/24